# configs/config.yaml
weights: "models/detrac_model.pt"   # Custom trained model
imgsz: 640
conf_threshold: 0.35
iou_threshold: 0.45
device: "cpu"                 # CPU only
count_line:                     # define counting line as two points (x,y)
  - [100, 300]
  - [1200, 300]
min_track_frames: 2
min_bbox_area: 400
class_names:
  - car
  - bus
  - van
  - others
